version: '3.1'
services:
  dbmain:
    container_name: dbmain
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'admin'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - 3306:3306
    volumes:
      - ./.data:/var/lib/mysql
